import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@dev,build,start,lint/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Acanthis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     

      {/* <h1 className="text-3xl font-bold underline">
      Hello world!
    </h1>

    <Image src="/images/Vector.png" max-width={500} max-height={500}  />  */}


       <main className= 'bg-[#f5fbff]'>
         <div className="px-16 py-6 w-96  sm:px-16 sm:py-6 sm:w-96 md:px-24 md:py-10 md:w-2/3 lg:px-36 lg:py-16 lg:w-2/3 xl:px-40 xl:py-20 xl:w-2/3">
          <h1 className='font-medium text-xl sm:font-medium sm:text-2xl md:font-bold md:text-3xl lg:font-extrabold lg:text-4xl xl:font-extrabold xl:text-5xl'>
          Get the visibility and guidance you need for your business</h1>

          <div className="py-6 font-thin text-[#4d4958]">
          Acanthis is a smart platform for SMEs that helps them make better decisions so they can stay ahead of the game.
          </div>
          <button class="text-xs py-1 px-2 sm:text-xs sm:py-1 sm:px-2 md:text-sm md:py-2 md:px-3 lg:text-lg lg:py-3 lg:px-4 xl:text-xl xl:py-4 xl:px-5 bg-[#FD4C00] hover:bg-[#ac2020e0] text-white font-thin border border-[#FD4C00] hover:border-transparent rounded">Learn More</button>
         </div>
     
      </main>  
    </>
  )
}
